services:
  backend:
    build: ./backend
    container_name: meli-backend-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code

  frontend:
    build: ./frontend
    container_name: meli-frontend-web
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
